# Site settings
title: The Academic Hermit
email: pschloss@umich.edu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pschloss.github.io" # the base hostname & protocol for your site
twitter_username: PatSchloss
github_username: pschloss

# Build settings
