# Site settings
title: Suck less...
email: pschloss@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Blog of Pat Schloss where he explores efforts at professional and personal improvement. Pat is a professor in the Department of Microbiology & Immunology at the University of Michigan where he [runs a lab](http://www.schlosslab.org). 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pschloss.github.io" # the base hostname & protocol for your site
twitter_username: pschloss
github_username:  pschloss

# Build settings
